// Lista de países com indicativo telefónico (DDI). Bandeira gerada a partir do iso2.
export type Country = { name: string; iso2: string; dial: string };

export const COUNTRIES: Country[] = [
  { name: "Afeganistão", iso2: "AF", dial: "+93" },
  { name: "África do Sul", iso2: "ZA", dial: "+27" },
  { name: "Albânia", iso2: "AL", dial: "+355" },
  { name: "Alemanha", iso2: "DE", dial: "+49" },
  { name: "Andorra", iso2: "AD", dial: "+376" },
  { name: "Angola", iso2: "AO", dial: "+244" },
  { name: "Anguila", iso2: "AI", dial: "+1" },
  { name: "Antígua e Barbuda", iso2: "AG", dial: "+1" },
  { name: "Arábia Saudita", iso2: "SA", dial: "+966" },
  { name: "Argélia", iso2: "DZ", dial: "+213" },
  { name: "Argentina", iso2: "AR", dial: "+54" },
  { name: "Arménia", iso2: "AM", dial: "+374" },
  { name: "Aruba", iso2: "AW", dial: "+297" },
  { name: "Austrália", iso2: "AU", dial: "+61" },
  { name: "Áustria", iso2: "AT", dial: "+43" },
  { name: "Azerbaijão", iso2: "AZ", dial: "+994" },
  { name: "Bahamas", iso2: "BS", dial: "+1" },
  { name: "Bangladexe", iso2: "BD", dial: "+880" },
  { name: "Barbados", iso2: "BB", dial: "+1" },
  { name: "Barém", iso2: "BH", dial: "+973" },
  { name: "Bélgica", iso2: "BE", dial: "+32" },
  { name: "Belize", iso2: "BZ", dial: "+501" },
  { name: "Benim", iso2: "BJ", dial: "+229" },
  { name: "Bermudas", iso2: "BM", dial: "+1" },
  { name: "Bielorrússia", iso2: "BY", dial: "+375" },
  { name: "Bolívia", iso2: "BO", dial: "+591" },
  { name: "Bósnia e Herzegovina", iso2: "BA", dial: "+387" },
  { name: "Botsuana", iso2: "BW", dial: "+267" },
  { name: "Brasil", iso2: "BR", dial: "+55" },
  { name: "Brunei", iso2: "BN", dial: "+673" },
  { name: "Bulgária", iso2: "BG", dial: "+359" },
  { name: "Burquina Faso", iso2: "BF", dial: "+226" },
  { name: "Burúndi", iso2: "BI", dial: "+257" },
  { name: "Butão", iso2: "BT", dial: "+975" },
  { name: "Cabo Verde", iso2: "CV", dial: "+238" },
  { name: "Camarões", iso2: "CM", dial: "+237" },
  { name: "Camboja", iso2: "KH", dial: "+855" },
  { name: "Canadá", iso2: "CA", dial: "+1" },
  { name: "Catar", iso2: "QA", dial: "+974" },
  { name: "Cazaquistão", iso2: "KZ", dial: "+7" },
  { name: "Chade", iso2: "TD", dial: "+235" },
  { name: "Chile", iso2: "CL", dial: "+56" },
  { name: "China", iso2: "CN", dial: "+86" },
  { name: "Chipre", iso2: "CY", dial: "+357" },
  { name: "Colômbia", iso2: "CO", dial: "+57" },
  { name: "Comores", iso2: "KM", dial: "+269" },
  { name: "Congo (Brazzaville)", iso2: "CG", dial: "+242" },
  { name: "Congo (Kinshasa)", iso2: "CD", dial: "+243" },
  { name: "Coreia do Norte", iso2: "KP", dial: "+850" },
  { name: "Coreia do Sul", iso2: "KR", dial: "+82" },
  { name: "Costa do Marfim", iso2: "CI", dial: "+225" },
  { name: "Costa Rica", iso2: "CR", dial: "+506" },
  { name: "Croácia", iso2: "HR", dial: "+385" },
  { name: "Cuba", iso2: "CU", dial: "+53" },
  { name: "Curaçau", iso2: "CW", dial: "+599" },
  { name: "Dinamarca", iso2: "DK", dial: "+45" },
  { name: "Domínica", iso2: "DM", dial: "+1" },
  { name: "Egito", iso2: "EG", dial: "+20" },
  { name: "Emirados Árabes Unidos", iso2: "AE", dial: "+971" },
  { name: "Equador", iso2: "EC", dial: "+593" },
  { name: "Eritreia", iso2: "ER", dial: "+291" },
  { name: "Eslováquia", iso2: "SK", dial: "+421" },
  { name: "Eslovénia", iso2: "SI", dial: "+386" },
  { name: "Espanha", iso2: "ES", dial: "+34" },
  { name: "Estados Unidos", iso2: "US", dial: "+1" },
  { name: "Estónia", iso2: "EE", dial: "+372" },
  { name: "Essuatíni", iso2: "SZ", dial: "+268" },
  { name: "Etiópia", iso2: "ET", dial: "+251" },
  { name: "Fiji", iso2: "FJ", dial: "+679" },
  { name: "Filipinas", iso2: "PH", dial: "+63" },
  { name: "Finlândia", iso2: "FI", dial: "+358" },
  { name: "França", iso2: "FR", dial: "+33" },
  { name: "Gabão", iso2: "GA", dial: "+241" },
  { name: "Gâmbia", iso2: "GM", dial: "+220" },
  { name: "Gana", iso2: "GH", dial: "+233" },
  { name: "Geórgia", iso2: "GE", dial: "+995" },
  { name: "Gibraltar", iso2: "GI", dial: "+350" },
  { name: "Granada", iso2: "GD", dial: "+1" },
  { name: "Grécia", iso2: "GR", dial: "+30" },
  { name: "Gronelândia", iso2: "GL", dial: "+299" },
  { name: "Guadalupe", iso2: "GP", dial: "+590" },
  { name: "Guame", iso2: "GU", dial: "+1" },
  { name: "Guatemala", iso2: "GT", dial: "+502" },
  { name: "Guiana", iso2: "GY", dial: "+592" },
  { name: "Guiana Francesa", iso2: "GF", dial: "+594" },
  { name: "Guiné", iso2: "GN", dial: "+224" },
  { name: "Guiné Equatorial", iso2: "GQ", dial: "+240" },
  { name: "Guiné-Bissau", iso2: "GW", dial: "+245" },
  { name: "Haiti", iso2: "HT", dial: "+509" },
  { name: "Honduras", iso2: "HN", dial: "+504" },
  { name: "Hong Kong", iso2: "HK", dial: "+852" },
  { name: "Hungria", iso2: "HU", dial: "+36" },
  { name: "Iémen", iso2: "YE", dial: "+967" },
  { name: "Ilhas Caimão", iso2: "KY", dial: "+1" },
  { name: "Ilhas Faroé", iso2: "FO", dial: "+298" },
  { name: "Ilhas Marshall", iso2: "MH", dial: "+692" },
  { name: "Ilhas Salomão", iso2: "SB", dial: "+677" },
  { name: "Ilhas Virgens Britânicas", iso2: "VG", dial: "+1" },
  { name: "Índia", iso2: "IN", dial: "+91" },
  { name: "Indonésia", iso2: "ID", dial: "+62" },
  { name: "Irão", iso2: "IR", dial: "+98" },
  { name: "Iraque", iso2: "IQ", dial: "+964" },
  { name: "Irlanda", iso2: "IE", dial: "+353" },
  { name: "Islândia", iso2: "IS", dial: "+354" },
  { name: "Israel", iso2: "IL", dial: "+972" },
  { name: "Itália", iso2: "IT", dial: "+39" },
  { name: "Jamaica", iso2: "JM", dial: "+1" },
  { name: "Japão", iso2: "JP", dial: "+81" },
  { name: "Jordânia", iso2: "JO", dial: "+962" },
  { name: "Kosovo", iso2: "XK", dial: "+383" },
  { name: "Kuwait", iso2: "KW", dial: "+965" },
  { name: "Laos", iso2: "LA", dial: "+856" },
  { name: "Lesoto", iso2: "LS", dial: "+266" },
  { name: "Letónia", iso2: "LV", dial: "+371" },
  { name: "Líbano", iso2: "LB", dial: "+961" },
  { name: "Libéria", iso2: "LR", dial: "+231" },
  { name: "Líbia", iso2: "LY", dial: "+218" },
  { name: "Listenstaine", iso2: "LI", dial: "+423" },
  { name: "Lituânia", iso2: "LT", dial: "+370" },
  { name: "Luxemburgo", iso2: "LU", dial: "+352" },
  { name: "Macau", iso2: "MO", dial: "+853" },
  { name: "Macedónia do Norte", iso2: "MK", dial: "+389" },
  { name: "Madagáscar", iso2: "MG", dial: "+261" },
  { name: "Malásia", iso2: "MY", dial: "+60" },
  { name: "Maláui", iso2: "MW", dial: "+265" },
  { name: "Maldivas", iso2: "MV", dial: "+960" },
  { name: "Mali", iso2: "ML", dial: "+223" },
  { name: "Malta", iso2: "MT", dial: "+356" },
  { name: "Marrocos", iso2: "MA", dial: "+212" },
  { name: "Maurícia", iso2: "MU", dial: "+230" },
  { name: "Mauritânia", iso2: "MR", dial: "+222" },
  { name: "México", iso2: "MX", dial: "+52" },
  { name: "Mianmar", iso2: "MM", dial: "+95" },
  { name: "Micronésia", iso2: "FM", dial: "+691" },
  { name: "Moçambique", iso2: "MZ", dial: "+258" },
  { name: "Moldávia", iso2: "MD", dial: "+373" },
  { name: "Mónaco", iso2: "MC", dial: "+377" },
  { name: "Mongólia", iso2: "MN", dial: "+976" },
  { name: "Montenegro", iso2: "ME", dial: "+382" },
  { name: "Namíbia", iso2: "NA", dial: "+264" },
  { name: "Nauru", iso2: "NR", dial: "+674" },
  { name: "Nepal", iso2: "NP", dial: "+977" },
  { name: "Nicarágua", iso2: "NI", dial: "+505" },
  { name: "Níger", iso2: "NE", dial: "+227" },
  { name: "Nigéria", iso2: "NG", dial: "+234" },
  { name: "Noruega", iso2: "NO", dial: "+47" },
  { name: "Nova Caledónia", iso2: "NC", dial: "+687" },
  { name: "Nova Zelândia", iso2: "NZ", dial: "+64" },
  { name: "Omã", iso2: "OM", dial: "+968" },
  { name: "Países Baixos", iso2: "NL", dial: "+31" },
  { name: "Palau", iso2: "PW", dial: "+680" },
  { name: "Palestina", iso2: "PS", dial: "+970" },
  { name: "Panamá", iso2: "PA", dial: "+507" },
  { name: "Papua-Nova Guiné", iso2: "PG", dial: "+675" },
  { name: "Paquistão", iso2: "PK", dial: "+92" },
  { name: "Paraguai", iso2: "PY", dial: "+595" },
  { name: "Peru", iso2: "PE", dial: "+51" },
  { name: "Polinésia Francesa", iso2: "PF", dial: "+689" },
  { name: "Polónia", iso2: "PL", dial: "+48" },
  { name: "Porto Rico", iso2: "PR", dial: "+1" },
  { name: "Portugal", iso2: "PT", dial: "+351" },
  { name: "Quénia", iso2: "KE", dial: "+254" },
  { name: "Quirguistão", iso2: "KG", dial: "+996" },
  { name: "Quiribáti", iso2: "KI", dial: "+686" },
  { name: "Reino Unido", iso2: "GB", dial: "+44" },
  { name: "República Centro-Africana", iso2: "CF", dial: "+236" },
  { name: "República Checa", iso2: "CZ", dial: "+420" },
  { name: "República Dominicana", iso2: "DO", dial: "+1" },
  { name: "Roménia", iso2: "RO", dial: "+40" },
  { name: "Ruanda", iso2: "RW", dial: "+250" },
  { name: "Rússia", iso2: "RU", dial: "+7" },
  { name: "Samoa", iso2: "WS", dial: "+685" },
  { name: "San Marino", iso2: "SM", dial: "+378" },
  { name: "Santa Lúcia", iso2: "LC", dial: "+1" },
  { name: "São Cristóvão e Neves", iso2: "KN", dial: "+1" },
  { name: "São Tomé e Príncipe", iso2: "ST", dial: "+239" },
  { name: "São Vicente e Granadinas", iso2: "VC", dial: "+1" },
  { name: "Seicheles", iso2: "SC", dial: "+248" },
  { name: "Senegal", iso2: "SN", dial: "+221" },
  { name: "Serra Leoa", iso2: "SL", dial: "+232" },
  { name: "Sérvia", iso2: "RS", dial: "+381" },
  { name: "Singapura", iso2: "SG", dial: "+65" },
  { name: "Síria", iso2: "SY", dial: "+963" },
  { name: "Somália", iso2: "SO", dial: "+252" },
  { name: "Sri Lanka", iso2: "LK", dial: "+94" },
  { name: "Sudão", iso2: "SD", dial: "+249" },
  { name: "Sudão do Sul", iso2: "SS", dial: "+211" },
  { name: "Suécia", iso2: "SE", dial: "+46" },
  { name: "Suíça", iso2: "CH", dial: "+41" },
  { name: "Suriname", iso2: "SR", dial: "+597" },
  { name: "Tailândia", iso2: "TH", dial: "+66" },
  { name: "Taiwan", iso2: "TW", dial: "+886" },
  { name: "Tajiquistão", iso2: "TJ", dial: "+992" },
  { name: "Tanzânia", iso2: "TZ", dial: "+255" },
  { name: "Timor-Leste", iso2: "TL", dial: "+670" },
  { name: "Togo", iso2: "TG", dial: "+228" },
  { name: "Tonga", iso2: "TO", dial: "+676" },
  { name: "Trindade e Tobago", iso2: "TT", dial: "+1" },
  { name: "Tunísia", iso2: "TN", dial: "+216" },
  { name: "Turquemenistão", iso2: "TM", dial: "+993" },
  { name: "Turquia", iso2: "TR", dial: "+90" },
  { name: "Tuvalu", iso2: "TV", dial: "+688" },
  { name: "Ucrânia", iso2: "UA", dial: "+380" },
  { name: "Uganda", iso2: "UG", dial: "+256" },
  { name: "Uruguai", iso2: "UY", dial: "+598" },
  { name: "Usbequistão", iso2: "UZ", dial: "+998" },
  { name: "Vanuatu", iso2: "VU", dial: "+678" },
  { name: "Vaticano", iso2: "VA", dial: "+379" },
  { name: "Venezuela", iso2: "VE", dial: "+58" },
  { name: "Vietname", iso2: "VN", dial: "+84" },
  { name: "Zâmbia", iso2: "ZM", dial: "+260" },
  { name: "Zimbábue", iso2: "ZW", dial: "+263" },
];

/** Bandeira emoji a partir do código iso2 (ex: "PT" -> 🇵🇹). */
export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}
